apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: v02506kjp-go-gitops
  description: This is GitOps manifest for v02506kjp-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=v02506kjp-go
    backstage.io/kubernetes-id: v02506kjp-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: v02506kjp-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:v02506kjp-go
